/**
 * Build the framework-agnostic token artifacts:
 *   - dist/tokens.json — full bundle for Figma plugins, marketing,
 *     non-JS consumers.
 *   - dist/tokens.css  — `:root { --rm8-* }` blocks for both schemes,
 *     wrapped in `[data-theme]` selectors so the website can switch
 *     with a class toggle.
 *
 * Invoked by `pnpm -F @rowerm8/design-tokens build`. The script reads
 * the same `lightTokens` / `darkTokens` objects that the in-app
 * provider uses, so the CSS / JSON outputs are always in sync with
 * the JS exports — no double source of truth.
 */

import { mkdirSync, writeFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

import { darkTokens, lightTokens, type ThemeTokens } from "../src/index";

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);
const PACKAGE_ROOT = resolve(__dirname, "..");
const DIST_DIR = resolve(PACKAGE_ROOT, "dist");

mkdirSync(DIST_DIR, { recursive: true });

writeFileSync(
  resolve(DIST_DIR, "tokens.json"),
  JSON.stringify({ light: lightTokens, dark: darkTokens }, null, 2) + "\n",
);

writeFileSync(resolve(DIST_DIR, "tokens.css"), buildCss());

console.log(`✓ wrote ${resolve(DIST_DIR, "tokens.json")}`);
console.log(`✓ wrote ${resolve(DIST_DIR, "tokens.css")}`);

function buildCss(): string {
  const banner =
    "/* AUTO-GENERATED by packages/design-tokens/scripts/build-tokens.ts. Do not edit. */\n\n";
  return (
    banner +
    schemeBlock(":root, [data-theme='light']", lightTokens) +
    "\n" +
    schemeBlock("[data-theme='dark']", darkTokens) +
    "\n"
  );
}

function schemeBlock(selector: string, tokens: ThemeTokens): string {
  const lines: string[] = [`${selector} {`];
  for (const [name, value] of flatten(tokens)) {
    lines.push(`  --rm8-${name}: ${value};`);
  }
  lines.push("}");
  return lines.join("\n") + "\n";
}

/**
 * Flatten the token tree into kebab-cased CSS variable names. Numbers
 * become `<n>px` (the spacing/radius scales are dp values that map 1:1
 * to web px); booleans and objects-of-numbers (motion easing tuples)
 * are emitted as comma-separated CSS values; nested objects (colors,
 * hr-zones) recurse with `-` joiners.
 */
function flatten(
  tokens: unknown,
  prefix = "",
): Generator<readonly [string, string]> {
  return walk(tokens, prefix);

  function* walk(
    node: unknown,
    pfx: string,
  ): Generator<readonly [string, string]> {
    if (node == null) {
      return;
    }
    if (typeof node === "string") {
      yield [pfx, node];
      return;
    }
    if (typeof node === "number") {
      yield [pfx, `${node}px`];
      return;
    }
    if (Array.isArray(node)) {
      yield [pfx, node.join(", ")];
      return;
    }
    if (typeof node === "object") {
      for (const [k, v] of Object.entries(node as Record<string, unknown>)) {
        const key = kebab(k);
        const next = pfx ? `${pfx}-${key}` : key;
        yield* walk(v, next);
      }
    }
  }
}

function kebab(input: string): string {
  return input
    .replace(/([a-z0-9])([A-Z])/g, "$1-$2")
    .replace(/_/g, "-")
    .toLowerCase();
}
